### ISSUE TITLE
Convert ResNet from MXNet to PyTorch

### ISSUE THREAD

**Issue by ahkarami** [rwightman/pytorch-dpn-pretrained#3]
Dear @rwightman,
Thank you for your nice repository. I have a pre-trained ResNet152 model on MXNet and I want to convert it to PyTorch. Would you please kindly guide me to do that?
In fact, I have used `convert_from_mxnet.py` to do that (by some little modification), however, I have faced the following error:
`AssertionError: Unexpected token`

**Comment by rwightman** [comment]
dump the model.state_dict() keys and tensor shapes, get a feel for the network structure

set debug=True on line 34

run the conversion and look what the last '...=>...' mapping is that's dumped before the error, try to match that up with your state key->tensor shape dump and see what the pattern is that the conditional isn't handling, add the necessary logic

**Comment by ahkarami** [comment]
Thank you for your time and response.
