### ISSUE TITLE
assert False when converting dpn107 by not finding 'num_batches_tracked'  in 'bn' converting function

### ISSUE THREAD

**Issue by popoala** [rwightman/pytorch-dpn-pretrained#5]
my environment is : anaconda3 with MXNET 1.1.0, pytorch 0.4.1
while running "python convert_from_mxnet.py ./pretrained --model dpn107", got

> Traceback (most recent call last):
>   File "convert_from_mxnet.py", line 136, in <module>
>     main()
>   File "convert_from_mxnet.py", line 129, in main
>     convert_from_mxnet(model, checkpoint_base)
>   File "convert_from_mxnet.py", line 51, in convert_from_mxnet
>     aux, key_add = _convert_bn(k[3])
>   File "convert_from_mxnet.py", line 31, in _convert_bn
>     assert False
> AssertionError

Then I tried to print more info, got:

> [17:04:05] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
> [17:04:05] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
> db now layer i:2,['features', 'conv1_1', 'bn', 'weight']
> db now layer i:3,['features', 'conv1_1', 'bn', 'bias']
> db now layer i:4,['features', 'conv1_1', 'bn', 'running_mean']
> db now layer i:5,['features', 'conv1_1', 'bn', 'running_var']
> db now layer i:6,['features', 'conv1_1', 'bn', 'num_batches_tracked']
> db in _convert_bn, k is num_batches_tracked
> Traceback (most recent call last):
>   File "convert_from_mxnet.py", line 136, in <module>
>     main()
>   File "convert_from_mxnet.py", line 129, in main
>     convert_from_mxnet(model, checkpoint_base)
>   File "convert_from_mxnet.py", line 51, in convert_from_mxnet
>     aux, key_add = _convert_bn(k[3])
>   File "convert_from_mxnet.py", line 31, in _convert_bn
>     assert False
> AssertionError

How to fix this?

**Comment by rwightman** [comment]
This must be a change in the batch norm layer in 0.4 version of PyTorch. There are a number of issues related to 'num_batches_tracked' that you can find if you google.

I don't have time to setup an environment and fix properly, but if you want to try
* modify _convert_bn() function and add a else branch to handle 'num_batches_tracked' key, just add the string as is, aux can remain False
* put an if block in front of line 91-92 as below

```
if mxnext_key.endswith('num_batches_tracked'):
  torch_tensor = torch.tensor(0, dtype=torch.long)
else:
  mxnet_array = mxnet_aux[mxnet_key] if aux else mxnet_weights[mxnet_key]
  torch_tensor = torch.from_numpy(mxnet_array.asnumpy())
```

That might do it, or something close to it...
